const ShopActionTypes = {
    FETCH_INITAL_COLLECTIONS: 'FETCH_INITAL_COLLECTIONS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_INITAL_COLLECTIONS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_INITAL_COLLECTIONS'
}

export default ShopActionTypes;